version=1.0.12
main.class=Start
classpath=client.jar;lib/*
java.args=-Xms512M|-Xmx2G|-Dfile.encoding=UTF-8
game.args=
file.count=1
file.0.path=.packages/client.zip
file.0.url=https://github.com/sals1k/desktop-runtime-assets/releases/download/runtime-1.0.12/runtime.zip
file.0.sha256=cb6551fa446229b052fa5ea2059778ea41bff67f5d4c10939b879ba3624bdee0
file.0.size=382035217
archive.count=1
archive.0.path=.packages/client.zip
archive.0.destination=.
