version=1.0.17
main.class=Start
classpath=client.jar;lib/*
java.args=-Xms512M|-Xmx2G|-Dfile.encoding=UTF-8
game.args=
file.count=1
file.0.path=.packages/client.zip
file.0.url=https://github.com/sals1k/desktop-runtime-assets/releases/download/runtime-1.0.17/runtime.zip
file.0.sha256=ebda64883805ffec6669810fb6c79a6b47dcf2ea55da772d574bb3832feba09d
file.0.size=381998742
archive.count=1
archive.0.path=.packages/client.zip
archive.0.destination=.
