version=1.0.15
main.class=Start
classpath=client.jar;lib/*
java.args=-Xms512M|-Xmx2G|-Dfile.encoding=UTF-8
game.args=
file.count=1
file.0.path=.packages/client.zip
file.0.url=https://github.com/sals1k/desktop-runtime-assets/releases/download/runtime-1.0.15/runtime.zip
file.0.sha256=0203c29cf223212033baf6c48b330a88a58da52734ed8c8b8a315e0b3d02cf2a
file.0.size=381998363
archive.count=1
archive.0.path=.packages/client.zip
archive.0.destination=.
